# Generated by Django 2.1.3 on 2018-11-15 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181114_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
