# Generated by Django 3.1.4 on 2020-12-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contest_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='time',
            new_name='start_time',
        ),
    ]
